-- MySQL Script generated by MySQL Workbench
-- Sun Jun 17 20:56:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `PersonId` INT NOT NULL DEFAULT 1,
  `Name` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL,
  `BloodGroup` VARCHAR(5) NULL,
  `UidNr` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `IsClient` BIT(1) NULL,
  PRIMARY KEY (`PersonId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UidNr_UNIQUE` ON `mydb`.`Person` (`UidNr` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `Adress` VARCHAR(4000) NULL,
  `Person_PersonId` INT NOT NULL,
  `State` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `PinCode` VARCHAR(45) NULL,
  `AddressType` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`AddressID`),
  CONSTRAINT `fk_Address_Person`
    FOREIGN KEY (`Person_PersonId`)
    REFERENCES `mydb`.`Person` (`PersonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Address_Person_idx` ON `mydb`.`Address` (`Person_PersonId` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `ContactId` INT NOT NULL AUTO_INCREMENT,
  `ContactNr` INT(15) NULL,
  `ContactNrType` VARCHAR(5) NOT NULL,
  `Person_PersonId` INT NOT NULL,
  `EmailId` VARCHAR(45) NULL,
  PRIMARY KEY (`ContactId`),
  CONSTRAINT `fk_Contact_Person1`
    FOREIGN KEY (`Person_PersonId`)
    REFERENCES `mydb`.`Person` (`PersonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Contact_Person1_idx` ON `mydb`.`Contact` (`Person_PersonId` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Documents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Documents` (
  `DocID` INT NULL AUTO_INCREMENT,
  `DocType` VARCHAR(10) NOT NULL,
  `DocNumber` VARCHAR(45) NOT NULL,
  `RenewalDate` DATE NOT NULL,
  `Location` VARCHAR(4000) NULL,
  `Person_PersonId` INT NOT NULL,
  `DocImage` BLOB NULL,
  `DOI` DATE NOT NULL,
  PRIMARY KEY (`DocID`),
  CONSTRAINT `fk_Documents_Person1`
    FOREIGN KEY (`Person_PersonId`)
    REFERENCES `mydb`.`Person` (`PersonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Documents_Person1_idx` ON `mydb`.`Documents` (`Person_PersonId` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`RefType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RefType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RefType` (
  `RefType` VARCHAR(10) NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RefType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Property` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Property` (
  `PropertyId` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(4000) NOT NULL,
  `CaretakerContactNR` INT NULL,
  `PurchaseDate` DATE NULL,
  `PurchaseCost` INT NULL,
  `CurrentValue` INT NULL,
  `AnnualExpense` INT NULL,
  `AnnualIncome` INT NULL,
  `Propertycol` VARCHAR(45) NULL,
  `SqFtArea` DECIMAL NULL,
  PRIMARY KEY (`PropertyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BankAccount` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BankAccount` (
  `BankAccountID` INT NOT NULL AUTO_INCREMENT,
  `AccountNr` INT NOT NULL,
  `NameofBank` VARCHAR(45) NOT NULL,
  `AddressofBank` VARCHAR(4000) NULL,
  `AccountType` VARCHAR(10) NOT NULL,
  `NameOfJointHolder` VARCHAR(45) NULL,
  `ModeOfOperation` VARCHAR(45) NULL,
  `LocationofPassbook` VARCHAR(45) NULL,
  `LocationofChequeBook` VARCHAR(45) NULL,
  PRIMARY KEY (`BankAccountID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `VehicleID` INT NOT NULL AUTO_INCREMENT,
  `VehicleNR` VARCHAR(45) NULL,
  `VehicleType` VARCHAR(45) NULL,
  `VehicleMake` VARCHAR(45) NULL,
  `VehicleModel` VARCHAR(45) NULL,
  `PurchaseDate` DATE NULL,
  `PurchaseValue` INT NULL,
  `ChassisNr` VARCHAR(45) NULL,
  `EngineNr` VARCHAR(45) NULL,
  `Vehiclecol` VARCHAR(45) NULL,
  PRIMARY KEY (`VehicleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VehicleInsurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VehicleInsurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VehicleInsurance` (
  `VehicleInsuranceID` INT NOT NULL AUTO_INCREMENT,
  `PolicyNR` VARCHAR(45) NOT NULL,
  `SumAssured` INT NULL,
  `PremiumAmount` INT NULL,
  `RenewalDate` DATE NULL,
  PRIMARY KEY (`VehicleInsuranceID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `PolicyNR_UNIQUE` ON `mydb`.`VehicleInsurance` (`PolicyNR` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Jewellery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jewellery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jewellery` (
  `JewelleryID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `JewelleryType` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `PurchanseDate` DATE NULL,
  `PurchanseValue` INT NULL,
  `ShopName` VARCHAR(45) NULL,
  `ShopAddress` VARCHAR(45) NULL,
  `LocationofJewellery` VARCHAR(45) NULL,
  `QuantityInGram` INT NULL,
  `PurchangeRateInRPG` DECIMAL(3) NULL,
  PRIMARY KEY (`JewelleryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BankLocker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BankLocker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BankLocker` (
  `BankLockerId` INT NOT NULL,
  `LockerNR` INT NULL,
  `LockerAddress` VARCHAR(45) NULL,
  `NameOfOperator` VARCHAR(45) NULL,
  `PlaceWhereKeysAreKept` VARCHAR(45) NULL,
  `RenewalDate` DATE NULL,
  `LockerRent` INT NULL,
  PRIMARY KEY (`BankLockerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClubMembership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ClubMembership` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ClubMembership` (
  `ClubMembershipID` INT NOT NULL,
  `NameofClub` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `TypeofClub` VARCHAR(10) NULL,
  `MembershipID` INT NULL,
  `RenewalDate` DATE NULL,
  `ClubRent` INT NULL,
  PRIMARY KEY (`ClubMembershipID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LifeInsurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LifeInsurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LifeInsurance` (
  `LifeInsuranceId` INT NOT NULL AUTO_INCREMENT,
  `PolicyNr` INT NOT NULL,
  `NameofScheme` VARCHAR(45) NULL,
  `PurchaseDate` DATE NULL,
  `SumAssured` INT NULL,
  `PremiumFrequency` VARCHAR(10) NULL,
  `PremiumAmount` INT NULL,
  `RenewalDate` DATE NULL,
  `Nominee` VARCHAR(45) NULL,
  `ExpiryDate` DATE NULL,
  `LifeInsurancecol` VARCHAR(45) NULL,
  PRIMARY KEY (`LifeInsuranceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedicalInsurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MedicalInsurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MedicalInsurance` (
  `MedicalInsuranceID` INT NOT NULL AUTO_INCREMENT,
  `PolicyNR` INT NOT NULL,
  `SchemeName` VARCHAR(45) NULL,
  `SumAssured` INT NULL,
  `PurchaseDate` DATE NULL,
  `PremiumAmount` INT NULL,
  `TPAContactNumber` INT NULL,
  `ExpiryDate` DATE NULL,
  PRIMARY KEY (`MedicalInsuranceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Investments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Investments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Investments` (
  `InvestmentsID` INT NOT NULL AUTO_INCREMENT,
  `SchemeName` VARCHAR(45) NULL,
  `InvestmentType` VARCHAR(10) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `InvestmentDate` DATE NULL,
  `MaturityDate` DATE NULL,
  `IsRecurring` VARCHAR(45) BINARY NOT NULL,
  `NameofNominee` VARCHAR(45) NULL,
  `NomineeRelationship` VARCHAR(45) NULL,
  `AccountNr` VARCHAR(45) NULL,
  `MaturityAmount` INT NULL,
  `InvestmentAmount` INT NULL,
  `RecurringAmount` INT NULL,
  `InterestRate` DECIMAL(3) NULL,
  PRIMARY KEY (`InvestmentsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MutualFunds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MutualFunds` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MutualFunds` (
  `MutualFundsId` INT NOT NULL,
  `FolioNr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MutualFundsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stocks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stocks` (
  `StocksId` INT NOT NULL,
  `DPId` VARCHAR(45) NULL,
  `ISIN` VARCHAR(45) NULL,
  PRIMARY KEY (`StocksId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Advisor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Advisor` (
  `FinancialAdvisorID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `ContactNr` INT NULL,
  `EmailId` VARCHAR(45) NULL,
  `TypeOfAdvisor` VARCHAR(10) NULL,
  PRIMARY KEY (`FinancialAdvisorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Loans` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `LoanId` INT NOT NULL,
  `NameOfPerson` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Amount` DECIMAL NULL,
  `DateOfLoan` DATE NULL,
  `InterestRate` DECIMAL(3) NULL,
  `Terms` VARCHAR(4000) NULL,
  `MaturityDate` DATE NULL,
  `LocationofLoanDocs` VARCHAR(1000) NULL,
  `Security` VARCHAR(45) NULL,
  `TypeOfLoan` VARCHAR(45) NULL COMMENT 'Granted or Taken',
  PRIMARY KEY (`LoanId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HouseHoldUtilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HouseHoldUtilities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HouseHoldUtilities` (
  `UtilitiesId` INT NOT NULL,
  `UtilityType` VARCHAR(10) NOT NULL,
  `RegistrationNr` VARCHAR(100) NULL,
  `UtilityName` VARCHAR(45) NULL,
  `ContactNr` VARCHAR(45) NULL,
  PRIMARY KEY (`UtilitiesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CreditDebitCards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CreditDebitCards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CreditDebitCards` (
  `CardId` INT NOT NULL,
  `CardNr` INT NULL,
  `IssuingBank` VARCHAR(45) NULL,
  `LinkedAccountNr` INT NULL,
  `TypeOfCard` VARCHAR(10) NULL,
  `IsActive` INT NULL,
  `CreditLimit` INT NULL,
  `ExpiryDate` DATE NULL,
  PRIMARY KEY (`CardId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CardNr_UNIQUE` ON `mydb`.`CreditDebitCards` (`CardNr` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`IncomeTaxRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IncomeTaxRecords` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IncomeTaxRecords` (
  `ITRecordsId` INT NOT NULL,
  `PANNr` VARCHAR(45) NULL,
  `LocationOfPAN` VARCHAR(45) NULL,
  `AY` YEAR NULL,
  `DueDate` DATE NULL,
  `ActualDate` DATE NULL,
  `GrossIncome` DECIMAL NULL,
  `TaxableIncome` DECIMAL NULL,
  `TaxDue` DECIMAL NULL,
  `TDS` DECIMAL NULL,
  `AdvanceTax` DECIMAL NULL,
  `AssessmentOrderDate` DATE NULL,
  `RefundAmount` DATE NULL,
  PRIMARY KEY (`ITRecordsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DPAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DPAccount` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DPAccount` (
  `DPId` INT NOT NULL,
  `DPName` VARCHAR(45) NULL,
  `DPAddress` VARCHAR(45) NULL,
  `ContactPerson` VARCHAR(45) NULL,
  `ContactNr` INT NULL,
  `JointHolderName` VARCHAR(45) NULL,
  `DPNumber` INT NULL,
  `DPFaxNr` INT NULL,
  PRIMARY KEY (`DPId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `DPNumber_UNIQUE` ON `mydb`.`DPAccount` (`DPNumber` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FamilyRelationships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FamilyRelationships` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FamilyRelationships` (
  `FamilyRelationId` INT NOT NULL,
  `ClientPersonId` INT NULL,
  `RelationPersonId` INT NULL,
  `IsEmergencyContact` BIT(1) NOT NULL,
  `RelationshipType` VARCHAR(10) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`FamilyRelationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EmployeeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonRelationAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PersonRelationAccess` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PersonRelationAccess` (
  `AccessId` INT NOT NULL,
  `SupportinDocument` BLOB NULL,
  `AccessGrantedOn` DATE NULL,
  `FamilyRelationId` INT NOT NULL,
  `EmployeeId` INT NOT NULL,
  PRIMARY KEY (`AccessId`, `FamilyRelationId`, `EmployeeId`),
  CONSTRAINT `fk_PersonRelationAccess_FamilyRelationships1`
    FOREIGN KEY (`FamilyRelationId`)
    REFERENCES `mydb`.`FamilyRelationships` (`FamilyRelationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PersonRelationAccess_Employee1`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `mydb`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PersonRelationAccess_FamilyRelationships1_idx` ON `mydb`.`PersonRelationAccess` (`FamilyRelationId` ASC);

CREATE INDEX `fk_PersonRelationAccess_Employee1_idx` ON `mydb`.`PersonRelationAccess` (`EmployeeId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
